### ISSUE TITLE
Ensure `neostandard` works without `typescript`

### ISSUE THREAD

**Issue by voxpelli** [neostandard/neostandard#124]
> @radek-duchon If you remove `ts: true` from your `neostandard` options, does it still complain?

Yes, it does. Using `ts` option does not play any role.

_Originally posted by @radek-duchon in https://github.com/neostandard/neostandard/issues/118#issuecomment-2263219303_

**Comment by voxpelli** [comment]
@radekduchon I would like to try and reproduce this, but doing a fresh installation with neostandard in a repository with no other dependencies still makes it work.

Are you using npm, yarn, pnpm?

I will try to reproduce it more

**Comment by voxpelli** [comment]
I successfully reproduced it using: `npm install --install-strategy nested`

**Comment by radek-duchon** [comment]
Sorry for not responding earlier. 👼  Yes I confirm that we use `npm` too.

**Comment by voxpelli** [comment]
I have a fix ready in #126, will merge it and release it as soon as all tests there has run
