### ISSUE TITLE
No issue.....just a thank you

### ISSUE THREAD

**Issue by sdcaulley** [neostandard/neostandard#132]
No issue.  Just a huge thank you.  I have loved (semi)standard for years, and it is so nice to see you moving the project forward.

**Comment by voxpelli** [comment]
Thanks a lot for the kind words @sdcaulley 🙏 Appreciate it a lot!

(Leaving open for a while longer so that other maintainers gets a chance to see it)

**Comment by voxpelli** [comment]
Thanks again for the kind words 🙏
