### ISSUE TITLE
prettier compat

### ISSUE THREAD

**Issue by ronag** [neostandard/neostandard#138]
We'd live to try this out and include it in our workflow. However, we are currently using prettier and would prefer to stick with that for now. Could we have a configuration with prettier compact?

**Comment by voxpelli** [comment]
There is the `noStyle` that will stop `neostandard` from caring about coding style and as such should behave well with eg prettier

I'm not a big user of prettier myself but would love for the combination to work well, can you elaborate on the addition you want? So that I'm sure I understand it 🙂

**Comment by jerome-benoit** [comment]
There's nothing to add to ensure neostandard works with prettier. It's just a matter of properly setting up the two:

- neostandard style: run prettier first then eslint 
- prettier style: run eslint first then prettier

Eslint configuration should be able to replicate that behavior by ordering neostandard and eslint prettier plugin configuration properly.

**Comment by voxpelli** [comment]
> There's nothing to add to ensure neostandard works with prettier

I’m interested to hear people’s thoughts and ideas on it nonetheless :)

**Comment by voxpelli** [comment]
If its the addition of [`eslint-config-prettier`](https://github.com/prettier/eslint-config-prettier) that you are asking about @ronag then the `noStyle` option is even better: It ensures no style rules gets added in the first place, so there's nothing for `eslint-config-prettier` to disable :)

This was extra easy now thanks to both ESLint itself and TypeScript-ESLint having deprecated their style rules and moved them to [`@stylistic/eslint-plugin`](https://eslint.style/packages/default), and setting `noStyle: true` disables the inclusion of `@stylistic/eslint-plugin` entirely

**Comment by jerome-benoit** [comment]
> > There's nothing to add to ensure neostandard works with prettier
> 
> I’m interested to hear people’s thoughts and ideas on it nonetheless :)

It's still an ESLint configuration issue, not an issue related to neostandard behavior. As I said in another issue: proposing a document compiling neostandard configuration with commonly used eslint plugins will address that kind of questions.

**Comment by voxpelli** [comment]
> It's still an ESLint configuration issue, not an issue related to neostandard behavior.

For most scenarios users should not have to care about the specifics of ESLint, sadly one still needs to since #33 is not done

**Comment by jerome-benoit** [comment]
> > It's still an ESLint configuration issue, not an issue related to neostandard behavior.
> 
> For most scenarios users should not have to care about the specifics of ESLint, sadly one still needs to since #33 is not done
 
Since it's a coding style project coming after existing ones and requiring major code lint/format tooling upgrade, all real world migrations to it are currently requiring users to do ESLint configuration, with plumbing most of the time because of project specificity. 

In the meantime, offering a kind of FAQ regarding neostandard configuration from GitHub issues will help migration to neostandard in most case.

**Comment by voxpelli** [comment]
Closing as the main issue question has been answered
