### ISSUE TITLE
Trailing comma in TypeScript enum not working as expected

### ISSUE THREAD

**Issue by shijinn520** [neostandard/neostandard#151]
Currently, trailing commas in TypeScript enums are not functioning as expected. The last comma is still being forcibly removed. When I include a trailing comma, I get the following error:

```
Unexpected trailing comma. eslint@stylistic/comma-dangle
```

**Comment by jerome-benoit** [comment]
Can you confirm that you are using the latest neostandard version released?

**Comment by voxpelli** [comment]
Agree that this should be ignored

The other three additions to the rule by TS are correct to ban though as I remember, did you check @jerome-benoit?

**Comment by voxpelli** [comment]
@shijinn520 Fix released 🙏

**Comment by jerome-benoit** [comment]
> The other three additions to the rule by TS are correct to ban though as I remember, did you check @jerome-benoit?

I think so but very unlikely to be met in real world code. The PR just address this issue for now.
