### ISSUE TITLE
no configuration mode

### ISSUE THREAD

**Issue by Eomm** [neostandard/neostandard#158]
Not sure it is doable, but, I would like a setup that works without any config file.

You install `neostandard` and you use its CLI.. and it is done.

**Comment by mcollina** [comment]
It's possible. See #2.

**Comment by voxpelli** [comment]
Tried to coordinate this with the wider ESLint community, but looks like we will have to do our own solution https://github.com/eslint/eslint/issues/18800

**Comment by voxpelli** [comment]
Tracking in #205 (sorry, forgot this one already existed)
