### ISSUE TITLE
Are there any plans to support TypeScript?

### ISSUE THREAD

**Issue by ridomin** [neostandard/neostandard#195]
I recently started using `ts-standard`, but seems it's not maintained anymore, after browsing the `standard` repo, I've found this one, and wondering if there are any plans to also support TypeScript.

**Comment by voxpelli** [comment]
TS is fully supported :) See the options for all the features you can opt into and out of: https://github.com/neostandard/neostandard#configuration-options

**Comment by ridomin** [comment]
well, I was looking for something like ts-standard, where I can run `npx ts-standard` without having to install any packages.

**Comment by voxpelli** [comment]
#33 tried to tackle this with the wider ESLint community but failed to describe it in a way that could be understood.

That took a lot of energy and time, now we instead have https://github.com/neostandard/neostandard/issues/205 tracking what you are mentioning

I’ll close this in favor of that for now then 🙏
