### ISSUE TITLE
eslint-plugin-import now supports ESLint v9

### ISSUE THREAD

**Issue by dead-claudia** [neostandard/neostandard#217]
https://github.com/import-js/eslint-plugin-import/releases/tag/v2.31.0

There are a few reports of brokenness in the v9 support (example: https://github.com/import-js/eslint-plugin-import/issues/3079), so it might not be possible to re-add *all* of it quite yet.

**Comment by jerome-benoit** [comment]
Please, do not open issue on already existing topic.

Dupe of #15

**Comment by dead-claudia** [comment]
Oh, sorry. Didn't realize this was too similar.
