### ISSUE TITLE
Improve how `eslint-import-resolver-typescript` is imported

### ISSUE THREAD

**Issue by voxpelli** [neostandard/neostandard#226]
The `eslint-plugin-import` / `eslint-plugin-import-x` should improve how the resolvers are defined in flat configs, it shouldn’t be a string: https://github.com/un-ts/eslint-plugin-import-x/blob/0bac033b5ff15f46cfb98760be24b3f33436e4a7/src/config/flat/typescript.ts#L27

_Originally posted by @voxpelli in https://github.com/neostandard/neostandard/pull/196#discussion_r1818153532_

_Follow up to https://github.com/neostandard/neostandard/pull/197#discussion_r1875934438_

**Comment by voxpelli** [comment]
Until then we could maybe use `require.resolve()` to resolve an absolute path and use when defining the resolver

_Originally posted by @voxpelli in https://github.com/neostandard/neostandard/pull/196#discussion_r1818153912_

**Comment by voxpelli** [comment]
Yeah, will have to make an issue there, but that's a task for another day.

Maybe we could do the `require.resolve()` before that to get an absolute path, or maybe it will all just work smoothly. Will do a release shortly with the import rules

**Comment by jerome-benoit** [comment]
> Looks like there is a fix now actually: [import-js/eslint-import-resolver-typescript#326](https://github.com/import-js/eslint-import-resolver-typescript/pull/326)

It's not working yet with `eslint-plugin-import`

**Comment by jerome-benoit** [comment]
> @jerome-benoit What was the reason we didn't go with `import-x`? What's your view on this? #231

Weird ESM module loading errors on canary repos testing with PR: https://github.com/neostandard/neostandard/pull/196.

**Comment by voxpelli** [comment]
@jerome-benoit Looks like its working with this? https://github.com/neostandard/neostandard/pull/231
