### ISSUE TITLE
Additional configurations handling

### ISSUE THREAD

**Issue by jerome-benoit** [neostandard/neostandard#23]
The options does not seems to allow to define custom configuration. 

Defining configuration that way: 

```js
[
  ...neostandard({
    globals: {
      ...globals.node,
    },
  }),
  js.configs.recommended,
  ...nodePlugin.configs['flat/mixed-esm-and-cjs'],
  jsdoc.configs['flat/recommended'],
  {
    plugins: {
      'simple-import-sort': simpleImportSort,
    },
    rules: {
      'simple-import-sort/imports': 'error',
      'simple-import-sort/exports': 'error',
    },
  },
]
```

works as long as there's no collision on readonly configuration keys . 

Since neostandard intention seems to build the eslint flat configuration and the outputs is not known, allowing to merge custom eslint flat configurations by giving a precedence to neostandard values would permit to build more easily complex configuration from neostandard helper. Or warn the user that the provided custom flat configuration is trying to override readonly keys foo, bar, ... 

Especially for the reusage of typescript-eslint shared configurations that expose keys collision with neostandard outputs.

**Comment by voxpelli** [comment]
What kind of error are you getting?

I'm doing a similar thing in my personal superset and have no issue: https://github.com/voxpelli/eslint-config/blob/main/index.js

**Comment by jerome-benoit** [comment]
With the configuration: 

```js
export default defineFlatConfig([
  cspellConfigs.recommended,
  js.configs.recommended,
  ...nodePlugin.configs['flat/mixed-esm-and-cjs'],
  jsdoc.configs['flat/recommended-typescript'],
  ...neostandard({
    ts: true,
    globals: {
      ...globals.node,
      ...globals.mocha
    },
    ignores: ['docs/**', 'dist/**', 'lib/**', 'outputs/**']
  }),
  ...tseslint.config(...tseslint.configs.strictTypeChecked, ...tseslint.configs.stylisticTypeChecked),
  {
    plugins: {
      'simple-import-sort': simpleImportSort
    },
    rules: {
      'simple-import-sort/imports': 'error',
      'simple-import-sort/exports': 'error',
    }
  }
])
```
finally narrowed it down to:

`Error: Error while loading rule '@typescript-eslint/await-thenable': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
Parser: undefined
Note: detected a parser other than @typescript-eslint/parser. Make sure the parser is configured to forward "parserOptions.project" to @typescript-eslint/parser.
Occurred while linting /home/fraggle/src/poolifier-git/.lintstagedrc.js`


I think I will be able to do a search and replace on the key to workaround it. I think the issue is on the typescript-eslint side alpha version that does not provides working configuration yet.

**Comment by jerome-benoit** [comment]
I confirm that typescript-eslint 8 alpha does not provide working configuration with type checking. 

What was the rationale for relying on that version? 
Would you take a PR for a dependabot configuration?

**Comment by voxpelli** [comment]
@jerome-benoit Only typescript-eslint 8.x supports ESLint 9, so anything lower would not have been guaranteed to work and would cause problem with incompatible peer dependency ranges.

The 8.x beta should be installed if you reinstall neostandard so that it install fresh subdependencies.

I can look into releasing a new version that requires it tomorrow (and set up depends / renovate, probably renovate)

**Comment by voxpelli** [comment]
Can also add: I want this to be fixed of course, one should be able to extend neostandard with type-aware linting if one wants to

**Comment by jerome-benoit** [comment]
I will test the 8 beta version with pnpm overrides to ensure the issue is addressed upstream.

**Comment by voxpelli** [comment]
The `^8.0.0-alpha.17` should match the beta, hence why I didn't urgently update it, so shouldn't have to do any override

**Comment by jerome-benoit** [comment]
Issue is between the chair and the keyboard: https://github.com/typescript-eslint/typescript-eslint/issues/9185#event-12992596095

**Comment by jerome-benoit** [comment]
The configuration provided by neostandard only works with type checking configuration provided by typescript-eslint if the ordering is: 


```js
 ...neostandard({
    ts: true,
    globals: {
      ...globals.node,
      ...globals.mocha,
    },
  }),
  ...tseslint.config(
    js.configs.recommended,
    ...tseslint.configs.strictTypeChecked,
    ...tseslint.configs.stylisticTypeChecked,
    {
      languageOptions: {
        parserOptions: {
          project: './tsconfig.json',
          tsconfigRootDir: import.meta.dirname
        }
      }
    }
  ),
```
