### ISSUE TITLE
Add default ignores?

### ISSUE THREAD

**Issue by voxpelli** [neostandard/neostandard#26]
`standard-engine` by default ignores [a couple of things](https://github.com/standard/standard-engine/blob/cf701384c130889b9107efe3a0c26c586dca588c/lib/resolve-eslint-config.js#L23-L28): 
```js
const DEFAULT_IGNORE = [
  '**/*.min.js',
  'coverage/**',
  'node_modules/**',
  'vendor/**'
]
```

ESLint by default ignores [`["**/node_modules/", ".git/"]`](https://eslint.org/docs/latest/use/configure/ignore#ignoring-files)

Neostandard currently includes the ESLint ones but not the `standard-engine` ones.

Should we add eg. ` **/*.min.js` and/or `coverage/**` or leave all ignoring to the user?

**Comment by mcollina** [comment]
Yes, let's do it

**Comment by voxpelli** [comment]
I'm pondering if we should add `dist/**` as well, as that's probably a more common compile output than `*.min.js` nowadays

`standard-engine` also ignores everything in ones `.gitignore` I think, but I don't think ESLint does that

**Comment by mcollina** [comment]
+1 to .gitignore.
