### ISSUE TITLE
Export default ignores and/or load plugins without ignore

### ISSUE THREAD

**Issue by voxpelli** [neostandard/neostandard#34]
In ESLint 9 the `ignore` is set in the config and not inherited by other configs.

This poses an issue when a second config wants to use a rule from the first config if the second config includes files that the first config ignored. A solution could have been to load the plugin in both the first and second config – but every plugin name is only allowed to be referenced once, so one has to either opt to load it oneself with a new name and then have entirely new rules, or opt for the same name to be able to override the rules, but then run the risk of a mismatching ignore making that plugin not always be loaded.

Hence why we currently use the `config()` command from `typescript-eslint` to merge our ignore into all the rules:

https://github.com/neostandard/neostandard/blob/64433273ce8c292a4337b2c2422f6c1dd078c07b/lib/main.js#L78-L90

But there's a catch with that:

Any config that wants to extend our config and modify or disable rules then needs to try and match our ignores, or else run into errors where the rule they are referring is not loaded.

I see two possible solutions:

* Always load plugins in a separate config that has no `ignore`, making them globally available
* Expose the default ignores so that a config extending this config can be sure to use the very same ignore and not get a mismatch

I'm myself torn a bit on this. Loading all the plugins separately feels like a bit of a hack. Exposing the ignores and relying on people using that across the board also feels a bit so-so though.

---

Ran into this with my own superset that I'm currently adapting to neostandard, and with `0.6.0` it started complaining about not finding rules and I quickly realized that was because of #26 / #29 where we added default ignores, as my modifications are of course then not adding the very same ignores

**Comment by mcollina** [comment]
I ended up doing https://github.com/fastify/fastify/pull/5509/files#diff-a32a0887ed9d1d707bbb3b845b7df7fd40e673c47e7b60a3ebd896b68d3b8839R14.

I think we might want to skip default ignores in this library.

**Comment by voxpelli** [comment]
I'm leaning towards that as well after having added them. Thoughts @bcomnes @wesleytodd @LinusU?

**Comment by voxpelli** [comment]
We could potentially offer `.gitignore` ignores through a helper function still, but I think that will also be available from ESLint: https://github.com/eslint/rewrite/pull/47

If its a common use case (which I think it is) it could be good to bundle the method that we currently have but expose it as a helper rather than include it internally

**Comment by bcomnes** [comment]
Exporting default ignores or helpers seems fine.
