### ISSUE TITLE
unmet peer dependency on eslint@8

### ISSUE THREAD

**Issue by mcollina** [neostandard/neostandard#35]
```
└─┬ neostandard 0.6.0
  └─┬ @stylistic/eslint-plugin 2.1.0
    └─┬ @stylistic/eslint-plugin-plus 2.1.0
      └─┬ @typescript-eslint/utils 7.12.0
        └── ✕ unmet peer eslint@^8.56.0: found 9.4.0
```

This is when using pnpm

**Comment by voxpelli** [comment]
Discovered that it had reappeared yesterday as well, reported it: https://github.com/eslint-stylistic/eslint-stylistic/issues/414

**Comment by jerome-benoit** [comment]
Is it actually causing any issues except a warning?

Because removing TS style support because of a peer dependency warning in a pre-release npm does not sound the right thing to do. Users can live with the warning, but without TS style support previously supported ...

**Comment by voxpelli** [comment]
@jerome-benoit Hopefully the stylistic team would move typescript-eslint to a peer dependency. I proposed that in their issue queue

**Comment by jerome-benoit** [comment]
Why not patch the package.json from upstream dep with `patch-package` as a temporary workaround? To avoid removing previously supported feature and installed the same deps with different  version.

**Comment by voxpelli** [comment]
Maybe we could fork the plugin until they officially release with typescript 8.x support, release it as `@neostandard/eslint-stylistic-ts` or something

**Comment by voxpelli** [comment]
@jerome-benoit Keeping track of it in https://github.com/neostandard/neostandard/issues/46 now :)
