### ISSUE TITLE
Reactivate stylistic rules for TypeScript

### ISSUE THREAD

**Issue by voxpelli** [neostandard/neostandard#46]
ESLint Stylistics TypeScript still rely on `typescript-eslint@^7` which in turn requires ESLint 8.x, which conflicts with our requirement of ESLint 9.x, hence we deactivated it in https://github.com/neostandard/neostandard/pull/36 to fix #35

When https://github.com/eslint-stylistic/eslint-stylistic/issues/414 has been fixed we can reintroduce them without getting peer dependency errors again (and as such get predictable outcomes)

Maybe we could fork ESLint Stylistics TypeScript until they officially release with typescript 8.x support and release it as `@neostandard/eslint-stylistic-ts` or something, to get support earlier

_Originally posted by @voxpelli in https://github.com/neostandard/neostandard/issues/35#issuecomment-2156625238_

**Comment by voxpelli** [comment]
Instead of forming we could of course also simply vendor it, that could be even better / simpler probably, but may be harder to keep in sync with upstream (unless we do git-subtree magic, which I happen to be quite proficient in 😎)

**Comment by jerome-benoit** [comment]
> Instead of forming we could of course also simply vendor it, that could be even better / simpler probably, but may be harder to keep in sync with upstream (unless we do git-subtree magic, which I happen to be quite proficient in 😎)

It depends on the bandwidth the maintainers have to maintain it. But I think avoiding to put more maintenance work is wise: upstream will at some point in time officially support the upcoming typescript-eslint version.
