### ISSUE TITLE
Can I fund this project

### ISSUE THREAD

**Issue by sacru2red** [neostandard/neostandard#51]
I'm not a native English speaker so I don't know exactly what it's called.
Can I fund this project?

I want to help, but I don't have the time or ability.

like [opencollective](https://opencollective.com/)

**Comment by bcomnes** [comment]
Soon. Subscribe to https://github.com/neostandard/neostandard/issues/21 and watch for future announcements. Thank you for your support!

**Comment by bcomnes** [comment]
Duplicate of https://github.com/neostandard/neostandard/issues/21
