### ISSUE TITLE
Checks in TypeScript files are not working

### ISSUE THREAD

**Issue by CalmLexi** [neostandard/neostandard#78]
I have checked the exported rules and found that all rules in neostandard/ts are turned off. When I manually enable them, the issue is resolved.

Here is my configuration:
```js
import neostandard, { resolveIgnoresFromGitignore } from 'neostandard'

export default neostandard({
  ignores: resolveIgnoresFromGitignore(),
  globals: ['logger'],
  ts: true,
})

```

Additionally, I would like to inquire if it is possible to make semicolons configurable?
```js
const obj = {
  a: 1,
  b: 2,  // commas can be omitted
}


```

**Comment by voxpelli** [comment]
All the style rules are currently deactivated in ts files, but will be reactivated when possible: https://github.com/neostandard/neostandard/issues/46

Regarding semicolons: You can set `semi: true` in the config to enforce semicolons rather than ban them 🙂

**Comment by voxpelli** [comment]
@CalmLexi Added #79 for comma dangle

**Comment by CalmLexi** [comment]
(*^▽^*)~
Thank you for your understanding and assistance.
