### ISSUE TITLE
Relax / revert `@stylistic/comma-dangle` to ease migration from `standard`

### ISSUE THREAD

**Issue by voxpelli** [neostandard/neostandard#79]
As both https://github.com/neostandard/neostandard/issues/78#issuecomment-2191373271 and https://github.com/fastify/fastify/pull/5509 mentioned, the enforcing of `comma-dangle` (that is one of two style related modernizations since `standard@17.x`) is a bit too prescriptive and maybe even controversial.

Related rule:

https://github.com/neostandard/neostandard/blob/3130ca90602bac53df18000c9a104ed2536ce85b/lib/configs/modernization.js#L23-L29

As mentioned in https://github.com/fastify/fastify/pull/5509#discussion_r1632056940 the equivalent in `standard@17.x` was:

```js
'@stylistic/comma-dangle': ['error', {
  arrays: 'never',
  objects: 'never',
  imports: 'never',
  exports: 'never',
  functions: 'never',
}],
```

https://github.com/neostandard/neostandard/issues/78#issuecomment-2191373271 suggests adding a configuration for the "legacy" behavior, something like `noCommaDangle: true` or `legacyCommaDangle: true`, but I don't like adding too many options.

Another option would be to simply disable the rule completely and conclude that there is no consistent approach to this within the community anymore.

A third is to revert it completely, but that would make projects that then override it not be `neostandard` compliant anymore.

---

I think its safe to say that the current state of it violates the mission statement (#7) of `Being a descriptive (not prescriptive) linting of common and good practices`

**Comment by jsumners** [comment]
Some thoughts:

1. Enforcing this by default results in many, some would say irrelevant, changes when applied to code base already using `standard`
2. I understand why people like it, but I really don't think it adds enough utility to overcome the aesthetics
3. I agree that adding options is a path toward "what's the point?" There should be as few options as possible

**Comment by voxpelli** [comment]
@jsumners Would you vote for removing the rule or to reverting to forbidding dangling commas?

**Comment by jsumners** [comment]
I think I would vote for removing the rule under the assumption that it would be the most permissive.

**Comment by bcomnes** [comment]
Can we leave it as a default-off option similar to semi rules?

**Comment by jerome-benoit** [comment]
People migrating to neostandard are warned about that style change from standard. And as such have implicilty agreed upon.   

But I do not see why neostandard could not offer: 

- modernisation -> neostandard rules
- standard -> legacy standard rules

On the implementation side, I do not think making a literal with boolean options to add is a good idea. It will make the life of users and maintainers better if: 

- a `style` option is added
- `style` can be:
  - modernisation ->  neostandard rules (default)
  - standard -> standard rules

The existing boolean seems to be orthogonal enough to the base style configuration to stay as is. But that can also be folded into the style namespace, such as modernisationsemi.

**Comment by voxpelli** [comment]
@jsumners @uzlopak Added a PR that disables the contentious ones: https://github.com/neostandard/neostandard/pull/139

**Comment by Uzlopak** [comment]
I personally prefer the dangling comma, but projects like undici would be about adding 3211 missing dangling commas. I dont think that this is nice for existing projects, basically pointing the blame to the one who migrates :-P

**Comment by voxpelli** [comment]
@Uzlopak Lets find a way to reintroduce them in a less intrusive way: #143

**Comment by jsumners** [comment]
> I personally prefer the dangling comma, but projects like undici would be about adding 3211 missing dangling commas. I dont think that this is nice for existing projects, basically pointing the blame to the one who migrates :-P

Given that eslint will add it on document save, this is the only real argument I can make against it. Adding it to projects that have not been using it results in way too many changes.
