### ISSUE TITLE
This deviates from eslint's doc's on how to combine configs

### ISSUE THREAD

**Issue by Jakobud** [neostandard/neostandard#92]
According to this here:

https://eslint.org/docs/latest/use/configure/combine-configs

The official eslint way of combining configs is

```
export default [
  config1,
  config2,
  config3,
  {
    ... // some override configs here
  }
];
```

But this `neostandard` says to do it like this:

```
export default neostandard({})
```

Why is this deviating so much? Why isn't this just a normal config that you can include like eslint describes? How do you combine neostandard with other configs and also have custom individual overrides?

Seems like this is more complicated than necessary. I dunno.

**Comment by mcollina** [comment]
`neostandard()` returns an array of configurations, so you can use it like the following:

```js
export default [
  ...neostandard({})
]
```

Do you think this should be mentioned?

**Comment by jerome-benoit** [comment]
Building a consistent configuration from various rules dispatched in several eslint plugins for JS, TS, JSX, TSX ... code base need some code to assess the consistency. typescript-eslint is using a similar approach by offering an helper to dedupe, ensure rules precedence, .... 

The output of `neostandard()` can be used as a standalone configuration in a more complex eslint setup.

**Comment by voxpelli** [comment]
@Jakobud I added a documentation suggestion in https://github.com/neostandard/neostandard/pull/94, would love your feedback on it :)

**Comment by voxpelli** [comment]
Merged and released it, but still interested in feedback @Jakobud :)
